name: Check Cruise Control new releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest release
        id: latest_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/linkedin/cruise-control/tags | jq -r '.[0].name')
          echo "latest_release=$latest_release" >> $GITHUB_OUTPUT

      - name: Get current release
        id: current_release
        run: |
          current_release=$(grep appVersion charts/cruise-control/Chart.yaml | awk '{ print $2 }')
          echo "current_release=$current_release" >> $GITHUB_OUTPUT

      - name: Check if release changed
        id: check_changes
        run: |
          if [ ${{ steps.latest_release.outputs.latest_release }} != ${{ steps.current_release.outputs.current_release }} ]; then
            echo "release_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Set new Chat.yaml appVersion
        if: steps.check_changes.outputs.release_changed == 'true'
        run: |
          sed -i "s/appVersion: .*/appVersion: jdk17-cc${{ steps.latest_release.outputs.latest_release }}/g" charts/cruise-control/Chart.yaml

      - name: Update README.md Helm Chart
        if: steps.check_changes.outputs.release_changed == 'true'
        uses: losisin/helm-docs-github-action@v1
        with:
          chart-search-root: charts/cruise-control

      - name: Create PR with changes
        if: steps.check_changes.outputs.release_changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_GITHUB }}
          commit-message: "fix: update Cruise Control version to ${{ steps.latest_release.outputs.latest_release }}"
          signoff: false
          branch: fix/upgrade-cruise-control-appversion-${{ steps.latest_release.outputs.latest_release }}
          delete-branch: true
          title: '[cruise-control] new release: ${{ steps.latest_release.outputs.latest_release }}'
          body: |
            Cruise Control version:
            - :information_source: Current: `${{ steps.current_release.outputs.current_release }}`
            - :up: Upgrade: `jdk17-cc${{ steps.latest_release.outputs.latest_release }}`

            Changelog: https://github.com/linkedin/cruise-control/releases/tag/${{ steps.latest_release.outputs.latest_release }}

            :warning: **BEFORE UPGRADE** :warning:
            Check the release is pushed on <https://github.com/devops-ia/kafka-cruise-control/pkgs/container/kafka-cruise-control>
          labels: |
            auto-pr-bump-version
          team-reviewers: devops-ia
